before:
  hooks:
    - go mod download

archives:
  - id: zip
    format: zip
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    wrap_in_directory: true

builds:
  - id: default
    goos:
      - darwin
      - linux
    ignore:
      - goos: darwin
        goarch: 386
      - goos: linux
        goarch: 386
    ldflags:
      - -X github.com/camerondurham/ch/version.PkgVersion={{ .Version }}
      - -X github.com/camerondurham/ch/version.GitRevision={{ .ShortCommit }}

  - id: windows
    goos:
      - windows
    ignore:
      - goos: windows
        goarch: 386
    ldflags:
      - -X github.com/camerondurham/ch/version.PkgVersion={{ .Version }}
      - -X github.com/camerondurham/ch/version.GitRevision={{ .ShortCommit }}

release:
  prerelease: auto

brews:
  -
    name: ch

    # NOTE: make sure the url_template, the token and given repo (github or gitlab) owner and name are from the
    # same kind. We will probably unify this in the next major version like it is done with scoop.

    tap:
      owner: camerondurham
      name: homebrew-tap
      branch: main
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    # url_template: "http://github.com/camerondurham/ch/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    folder: Formula
    homepage: "https://github.com/camerondurham/ch"
    description: "Docker config and shell manager for using (or misusing) containers as dev environments"
    license: "Apache-2.0"
    skip_upload: auto
    test: |
      system "#{bin}/ch --version"
    install: |
      bin.install "ch"
