// Code generated by MockGen. DO NOT EDIT.
// Source: ./validate.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockValidate is a mock of Validate interface.
type MockValidate struct {
	ctrl     *gomock.Controller
	recorder *MockValidateMockRecorder
}

// MockValidateMockRecorder is the mock recorder for MockValidate.
type MockValidateMockRecorder struct {
	mock *MockValidate
}

// NewMockValidate creates a new mock instance.
func NewMockValidate(ctrl *gomock.Controller) *MockValidate {
	mock := &MockValidate{ctrl: ctrl}
	mock.recorder = &MockValidateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValidate) EXPECT() *MockValidateMockRecorder {
	return m.recorder
}

// GetAbs mocks base method.
func (m *MockValidate) GetAbs(arg0 string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAbs", arg0)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetAbs indicates an expected call of GetAbs.
func (mr *MockValidateMockRecorder) GetAbs(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAbs", reflect.TypeOf((*MockValidate)(nil).GetAbs), arg0)
}

// ValidPath mocks base method.
func (m *MockValidate) ValidPath(arg0 string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidPath", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ValidPath indicates an expected call of ValidPath.
func (mr *MockValidateMockRecorder) ValidPath(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidPath", reflect.TypeOf((*MockValidate)(nil).ValidPath), arg0)
}
