name: Homebrew Bump Formula
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: "ch release version"
      sha:
        required: true
        description: "ch release git SHA"

jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: macos-latest
    steps:
      - uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          token: ${{ secrets.BUILDBOT_GITHUB_TOKEN }}
          formula: ch
          org: camerondurham
          tag: ${{ github.event.inputs.version }}
          revision: ${{ github.event.inputs.sha }}
