name: Release Package
on:
  push:
      # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:

  linux-windows-build:
    name: Linux & Windows Build
    runs-on: ubuntu-latest
    steps:

      - name: Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16beta1
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Exit if not from main branch
        if: endsWith(github.ref, 'main') == false
        run: exit -1

      - name: Make Linux
        run: export PATH=/home/runner/go/bin/:$PATH && make linux

      - name: Make Windows
        run: export PATH=/home/runner/go/bin/:$PATH && make windows

      - name: Package
        run: make zip_exe

      - name: Windows amd64
        uses: actions/upload-artifact@v2
        with:
          name: ch-windows-amd64
          path: ./dist/ch-windows-amd64.zip

      - name: Linux amd64
        uses: actions/upload-artifact@v2
        with:
          name: ch-linux-amd64
          path: ./dist/ch-linux-amd64.zip

      - name: Linux arm64
        uses: actions/upload-artifact@v2
        with:
          name: ch-linux-arm64
          path: ./dist/ch-linux-arm64.zip

  macos-build:
    name: MacOS Build
    runs-on: macos-latest
    steps:

      - name: Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16beta1
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Make Darwin
        run: export PATH=/Users/runner/go/bin/:$PATH && make macos

      - name: Package
        run: make zip_exe

      - name: MacOS amd64
        uses: actions/upload-artifact@v2
        with:
          name: ch-darwin-amd64
          path: ./dist/ch-darwin-amd64.zip

      - name: MacOS arm64
        uses: actions/upload-artifact@v2
        with:
          name: ch-darwin-arm64
          path: ./dist/ch-darwin-arm64.zip

  tagged-release:

    needs: [linux-windows-build, macos-build]

    name: "Tagged Release"
    runs-on: ubuntu-latest

    steps:
      - run: mkdir -p ./artifacts && mkdir -p ./release
      - uses: actions/download-artifact@v2
        with:
          path: ./artifacts

      - name: Copy files
        run: |
          cp ./artifacts/*/*.zip ./release

      - name: Publish Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            ./release/*.zip
